parameters:
  - name: environment
    type: string
    values:
      - dev
      - staging
  - name: agentPool
    type: string
    default: "CMRC PreProd Pool"

jobs:
  - job: runE2ETests
    displayName: "Run E2E Tests with Playwright"
    pool: ${{ parameters.agentPool }}
    variables:
      - group: cmrc-automated-testing-${{ parameters.environment }}
      - group: cmrc-backend-config-${{ parameters.environment }}
      - group: cmrc-ui-config-${{ parameters.environment }}
      - name: nodeVersion
        value: "24.x"
      - name: workingDir
        value: "$(System.DefaultWorkingDirectory)/src/ui-spa"

    steps:
      - task: UseNode@1
        displayName: "Use Node.js"
        inputs:
          version: "$(nodeVersion)"

      - task: Npm@1
        displayName: "Install NPM Dependencies"
        inputs:
          command: "ci"
          workingDir: "$(workingDir)"

      - script: node_modules/.bin/playwright install --with-deps chromium
        displayName: "Install Browsers"
        workingDirectory: $(workingDir)

      - script: npm run e2e:test:ci
        workingDirectory: $(workingDir)
        displayName: "Run E2E Tests"
        env:
          E2E_FRONTEND_URL: $(RedirectUrlRegisterCaseUi)
          E2E_API_BASE_URL: $(VITE_GATEWAY_BASE_URL)
          E2E_AAD_USERNAME: $(AadUserName)
          E2E_AAD_PASSWORD: $(AadUserPassword)
          E2E_CMS_USERNAME: $(CmsUserName)
          E2E_CMS_PASSWORD: $(CmsUserPassword)

      - task: PublishTestResults@2
        displayName: "Publish Test Results (JUnit)"
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "$(workingDir)/e2e-tests/e2e-test-results.xml"
          publishRunAttachments: false
        condition: succeededOrFailed()

      - publish: "$(workingDir)/e2e-tests/playwright-report"
        artifact: "$(System.JobId)-e2e-playwright-report"
        displayName: "Publish Report Artifact"
        condition: succeededOrFailed()
