trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - src/backend/*

pr: none

variables:
  - group: "cmrc-deployment-global"
  - name: "buildConfiguration"
    value: "Release"
  - name: "dotNetVersion"
    value: "10.x"
  - name: "buildArtifact"
    value: "cmrc-main-api-drop"

stages:
  - stage: Build
    displayName: "Build Main API"
    pool: "CMRC PreProd Pool"
    jobs:
      - job: Build_Main_API
        displayName: "Build Main API"
        steps:
          - template: ../templates/dotnet-build-steps.yml
            parameters:
              projectPath: "src/backend/Cps.CaseManagement.Api/Cps.CaseManagement.Api.csproj"
              projectName: $(buildArtifact)
              dotNetVersion: $(dotNetVersion)
              publishOutput: true
              runTests: false
              releaseVersionArg: "/p:Version=$(releaseVersion)"
              releaseSourceVersionArg: "/p:SourceRevisionId=$(Build.SourceVersion)"

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      buildStageName: "Build"
      environment: "staging"
      deployToSlot: true
      slotName: "stg"
      buildArtifact: $(buildArtifact)

  - stage: Release_Gate
    displayName: "Release Gate"
    jobs:
      - job: Manual_Validation
        pool: server
        timeoutInMinutes: 6500
        steps:
          - task: ManualValidation@1
            displayName: Request Validation
            timeoutInMinutes: 6480
            inputs:
              notifyUsers: $(prodNotifyUsers)
              approvers: $(prodApprovers)
              allowApproversToApproveTheirOwnRuns: true
              instructions: "Approval is required to deploy to production."
              onTimeout: "reject"

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      buildStageName: "Build"
      environment: "prod"
      agentPool: "CMRC Prod Pool"
      azureSubscription: "Azure Pipeline: CMRC - Prod"
      deployToSlot: true
      slotName: "stg"
      buildArtifact: $(buildArtifact)
