trigger: none

pr:
  branches:
    include:
      - main
      - development
  paths:
    include:
      - src/backend/*
      - src/tests/*

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '10.x'
  testResultsDirectory: '$(Agent.TempDirectory)/TestResults'

pool: 'CMRC PreProd Pool'

stages:
  - stage: Build_And_Test_Backend
    displayName: 'Build, Test & Package'
    jobs:
      - job: Build_And_Test_Solution
        displayName: 'Build & Test Solution'
        steps:
          - template: ../templates/dotnet-build-steps.yml
            parameters:
              projectPath: 'src/backend/Cps.CaseManagement.sln'
              projectName: 'Backend Solution'
              dotNetVersion: $(dotNetVersion)
              publishOutput: false
              runTests: true
              checkFormatting: true
              testResultsDirectory: $(testResultsDirectory)
